plugins {
    id("org.jetbrains.kotlinx.kover")
}

// Kover instruments the JVM compilation and collects coverage from jvmTest.
// Reports are generated by koverHtmlReportJvm / koverXmlReportJvm.
// Coverage thresholds can be enforced per-module via koverReport { verify { } }
// once baselines are established; this convention intentionally leaves that to each module.
kover {
    reports {
        filters {
            excludes {
                // Generated SQLDelight code and Compose-generated classes produce noise.
                packages(
                    "com.jepittman.tempo.core.database.sqldelight",
                )
                annotatedBy("androidx.compose.runtime.Composable")
            }
        }
    }
}
